### ISSUE TITLE
getting an ESM error when trying to use the library...

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#4]
getting the following error in the terminal when trying to use the library:

```bash
[vite] Error when evaluating SSR module /Users/rchrdnsh/Code/Svelte/RYKR-kit/src/routes/stripe.svelte:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/svelte-stripe-js/index.js
require() of ES modules is not supported.
require() of /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/svelte-stripe-js/index.js from /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/svelte-stripe-js/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1126:13)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (/Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73479:17)
    at ssrImport (/Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73431:20)
    at eval (/Users/rchrdnsh/Code/Svelte/RYKR-kit/src/routes/stripe.svelte:12:31)
    at instantiateModule (/Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73464:166)
Must use import to load ES Module: /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/svelte-stripe-js/index.js
require() of ES modules is not supported.
require() of /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/svelte-stripe-js/index.js from /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-c1a9de64.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/svelte-stripe-js/package.json.
```

...dunno if there is something that I need to do differently, as I have really only copied and pasted your code example so far...

I'm on the latest version of sveltekit, which at this moment is 144...

**Comment by joshnuss** [comment]
Hey @rchrdnsh,

Did you configure `noExternals` in `vite.config.js`? It's the second code listing here: https://github.com/joshnuss/svelte-stripe-js/#svelte-kit

**Comment by rchrdnsh** [comment]
hmmm...I copied and pasted it from your example earlier, and I notice now that `noexternal` is what was there, but it's now fixed to be `noExternal`, which gets rid of the error. Thanks for the quick fix and quick help! :-)

**Comment by rchrdnsh** [comment]
I will close this now :-)

**Comment by joshnuss** [comment]
Awesome, glad it's fixed.

Let me know if you bump into anything else,
