### ISSUE TITLE
Failed to resolve entry for package (SvelteKit / Vite)

### ISSUE THREAD

**Issue by didier** [joshnuss/svelte-stripe-js#8]
Hey, I just tried to start a fresh SvelteKit project with this package. Upon running, I encountered the following error using your example code:

```
yarn run v1.22.5
warning package.json: No license field
$ svelte-kit dev
 > node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38757:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "svelte-stripe-js". The package may have incorrect main/module/exports specified in its package.json.
    38757 │         throw new Error(`Failed to resolve entry for package "${id}". ` +
          ╵               ^
    at resolvePackageEntry (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38757:15)
    at tryNodeResolve (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38576:11)
    at Context.resolveId (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38459:28)
    at Object.resolveId (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:50882:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:51079:26)
    at async /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:51181:34
    at async callback (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:812:28)
    at async handleRequest (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:644:30)

   node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:51171:18: note: This error came from the "onResolve" callback registered here
    51171 │             build.onResolve({
          ╵                   ~~~~~~~~~
    at setup (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:51171:19)
    at handlePlugins (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:736:23)
    at Object.buildOrServe (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1024:7)
    at /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1754:17
    at new Promise (<anonymous>)
    at Object.build (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1753:14)
    at Object.build (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1629:51)
    at /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:51039:54
    at Array.map (<anonymous>)

   html:/Users/didier/Projects/Experiments/stripe/src/routes/index.svelte:2:61: note: The plugin "vite:dep-scan" was triggered by this import
        2 │   import { Container, CardNumber, CardExpiry, CardCvc } from 'svelte-stripe-js'
          ╵                                                              ~~~~~~~~~~~~~~~~~~

> Build failed with 1 error:
node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38757:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "svelte-stripe-js". The package may have incorrect main/module/exports specified in its package.json.
Error: Build failed with 1 error:
node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:38757:14: error: [plugin: vite:dep-scan] Failed to resolve entry for package "svelte-stripe-js". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1449:15)
    at /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1129:7)
    at /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:1236:14
    at /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/esbuild@0.12.19/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:470:12)
file:///Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.146_svelte@3.42.1/node_modules/@sveltejs/kit/dist/chunks/index.js:3373
                        throw new Error('Cannot close server before it is initialized');
                              ^

Error: Cannot close server before it is initialized
    at Watcher.close (file:///Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.146_svelte@3.42.1/node_modules/@sveltejs/kit/dist/chunks/index.js:3373:10)
    at process.<anonymous> (file:///Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.146_svelte@3.42.1/node_modules/@sveltejs/kit/dist/chunks/index.js:3199:9)
    at process.emit (node:events:394:28)
    at process.emit (node:domain:470:12)
    at process.exit (node:internal/process/per_thread:184:15)
    at handle_error (file:///Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.146_svelte@3.42.1/node_modules/@sveltejs/kit/dist/cli.js:851:10)
    at file:///Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.146_svelte@3.42.1/node_modules/@sveltejs/kit/dist/cli.js:903:4
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by joshnuss** [comment]
Hey @didier,

Good catch. I think I ran `npm publish` which sent the entire svelte-kit app to npm, when I meant to run `npm run publish`, which only sends the `package/` folder. doh.
 
It should be fixed now, can you bump the version you are using to `0.0.8`?

**Comment by didier** [comment]
Ha—happens to the best of us. That did fix the issue, however, I'm getting ES Module errors now. Not doing any `require()`s myself.
```
500
Must use import to load ES Module: /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/svelte-stripe-js@0.0.8/node_modules/svelte-stripe-js/index.js
require() of ES modules is not supported.
require() of /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/svelte-stripe-js@0.0.8/node_modules/svelte-stripe-js/index.js from /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/svelte-stripe-js@0.0.8/node_modules/svelte-stripe-js/package.json.
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/svelte-stripe-js@0.0.8/node_modules/svelte-stripe-js/index.js
require() of ES modules is not supported.
require() of /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/svelte-stripe-js@0.0.8/node_modules/svelte-stripe-js/index.js from /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/svelte-stripe-js@0.0.8/node_modules/svelte-stripe-js/package.json.

    at new NodeError (node:internal/errors:363:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:13)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73479:17)
    at ssrImport (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73431:20)
    at eval (/Users/didier/Projects/Experiments/stripe/src/routes/index.svelte:7:31)
    at instantiateModule (/Users/didier/Projects/Experiments/stripe/node_modules/.pnpm/vite@2.4.4/node_modules/vite/dist/node/chunks/dep-c1a9de64.js:73464:166)
```

**Comment by joshnuss** [comment]
Have you added `svelte-stripe-js` to `noExternals` in `svelte.config.js`?
https://github.com/joshnuss/svelte-stripe-js#svelte-kit

**Comment by didier** [comment]
Oh, oops. Missed that 🤦‍♂️. Works like a charm now!

**Comment by joshnuss** [comment]
:raised_hands: awesome!

LMK if you bump into anything else.

**Comment by joshnuss** [comment]
Also, I've [updated the README](4ea8171b55642a85b62063cc7f41e4157ce4f03a) to move info about svelte-kit higher, since it's probably what most people want to use.
